- name: daemon-reload
  command: systemctl daemon-reload

- name: docker
  service: name=docker enabled=yes state=restarted

- name: etcd
  service: name=etcd enabled=yes state=restarted

- name: kubelet
  service: name=kubelet enabled=yes state=restarted

- name: kube-proxy
  service: name=kube-proxy enabled=yes state=restarted

- name: calico-node
  service: name=calico-node enabled=yes state=restarted
