- hosts: all
  remote_user: admin
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - kube

- hosts: master
  remote_user: admin
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - kube-master

- hosts: minion
  remote_user: admin
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - kube-minion
