apiVersion: v1
kind: Pod
metadata:
  name: kube-master
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: apiserver
    image: gcr.io/google_containers/hyperkube:{{ kube_release }}
    command:
    - /hyperkube
    - apiserver
    - --portal-net=10.0.0.1/24
    - --address={{ kube_master_ip }}
    - --etcd-servers=http://127.0.0.1:4001
    - --cluster-name=kubernetes
    - --service-node-port-range=0-65535
    - --v=2
  - name: controller-manager
    image: gcr.io/google_containers/hyperkube:{{ kube_release }}
    command:
    - /hyperkube
    - controller-manager
    - --master={{ kube_master_ip }}:8080
    - --v=2
  - name: scheduler
    image: gcr.io/google_containers/hyperkube:{{ kube_release }}
    command:
    - /hyperkube
    - scheduler
    - --master={{ kube_master_ip }}:8080
    - --v=2
